// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210717095825_PasswordAdded")]
    partial class PasswordAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatumRodjenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MjestoStanovanja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Prezime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumUnosaDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<string>("FizickoLice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .HasColumnType("TEXT");

                    b.Property<string>("NaslovDokumenta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Posiljaoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Primaoc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Vrijednost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("korisnikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("korisnikId");

                    b.ToTable("Docs");
                });

            modelBuilder.Entity("API.Entities.Documents", b =>
                {
                    b.HasOne("API.Entities.AppUser", "korisnik")
                        .WithMany()
                        .HasForeignKey("korisnikId");

                    b.Navigation("korisnik");
                });
#pragma warning restore 612, 618
        }
    }
}
